// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: seats.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PostSeatsClient is the client API for PostSeats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostSeatsClient interface {
	PostSeats(ctx context.Context, in *SeatRequest, opts ...grpc.CallOption) (*SeatResponse, error)
}

type postSeatsClient struct {
	cc grpc.ClientConnInterface
}

func NewPostSeatsClient(cc grpc.ClientConnInterface) PostSeatsClient {
	return &postSeatsClient{cc}
}

func (c *postSeatsClient) PostSeats(ctx context.Context, in *SeatRequest, opts ...grpc.CallOption) (*SeatResponse, error) {
	out := new(SeatResponse)
	err := c.cc.Invoke(ctx, "/pb.PostSeats/PostSeats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostSeatsServer is the server API for PostSeats service.
// All implementations must embed UnimplementedPostSeatsServer
// for forward compatibility
type PostSeatsServer interface {
	PostSeats(context.Context, *SeatRequest) (*SeatResponse, error)
	mustEmbedUnimplementedPostSeatsServer()
}

// UnimplementedPostSeatsServer must be embedded to have forward compatible implementations.
type UnimplementedPostSeatsServer struct {
}

func (UnimplementedPostSeatsServer) PostSeats(context.Context, *SeatRequest) (*SeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostSeats not implemented")
}
func (UnimplementedPostSeatsServer) mustEmbedUnimplementedPostSeatsServer() {}

// UnsafePostSeatsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostSeatsServer will
// result in compilation errors.
type UnsafePostSeatsServer interface {
	mustEmbedUnimplementedPostSeatsServer()
}

func RegisterPostSeatsServer(s grpc.ServiceRegistrar, srv PostSeatsServer) {
	s.RegisterService(&PostSeats_ServiceDesc, srv)
}

func _PostSeats_PostSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSeatsServer).PostSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSeats/PostSeats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSeatsServer).PostSeats(ctx, req.(*SeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostSeats_ServiceDesc is the grpc.ServiceDesc for PostSeats service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostSeats_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PostSeats",
	HandlerType: (*PostSeatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostSeats",
			Handler:    _PostSeats_PostSeats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seats.proto",
}
